datafile: C:\3_Nf1_project\0_DataStructure_updated\Nf1_all_07052024.h5

output: C:\3_Nf1_project\0_DataStructure_updated\coordinates\

plot_folder: C:\3_Nf1_project\0_DataStructure_updated\plots\
data_folder: ./data/